[package]
name = "scarb-proc-macro-server-types"
version = "0.3.0-rc.0"
description = "Types for interacting with an RPC server set up by the `scarb proc-macro-server` command."
readme = "README.md"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cairo-lang-macro = { path = "../../plugins/cairo-lang-macro", version = "0.2.0-rc.0",  features = ["serde"] }
cairo-lang-macro-v1.workspace = true
serde.workspace = true
serde_json.workspace = true
