[package]
name = "oracle"
version = "0.1.0"
edition = "2024_07"
description = "Interfaces for calling external oracles"
authors = ["Software Mansion <contact@swmansion.com>"]
homepage = "https://docs.swmansion.com/scarb"
license = "MIT"
repository = "https://github.com/software-mansion/scarb"
