[package]
name = "scarb-stable-hash"
version = "1.0.0"
description = "Implementation of a hasher that produces the same values across Scarb releases"
readme = "README.md"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
xxhash-rust.workspace = true
data-encoding.workspace = true
