[package]
name = "scarb-cairo-language-server"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
cairo-lang-language-server.workspace = true
cairo-lang-utils.workspace = true
log.workspace = true
tokio.workspace = true
