[alias]
xtask = "run --quiet --package xtask --"

# On Windows MSVC, statically link the C runtime so that the resulting EXE does
# not depend on the vcruntime DLL.
[target.'cfg(windows)']
rustflags = ["-C", "target-feature=+crt-static"]
