[package]
name = "once_map"
version = "0.0.1"
publish = false
edition.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dashmap.workspace = true
tokio.workspace = true
futures.workspace = true
