//! Static contract forwarding: injects forwarding targets' class hashes into dependents' Sierra
//! generation via the reserved `__externally_provided_const__` extern. The per-contract
//! class-hash accessor is generated by Scarb (`plugin::class_hash_forwarding`), not Cairo.

use anyhow::{Context, Result, bail, ensure};
use cairo_lang_compiler::diagnostics::DiagnosticsReporter;
use cairo_lang_compiler::{CompilerConfig, ensure_diagnostics};
use cairo_lang_defs::ids::{ExternFunctionId, TopLevelLanguageElementId};
use cairo_lang_diagnostics::Maybe;
use cairo_lang_semantic::TypeId;
use cairo_lang_semantic::items::constant::ConstValueId;
use cairo_lang_sierra_generator::db::{
    EXTERNALLY_PROVIDED_CONST, ExternalConstPlugin, SierraGenGroup,
};
use cairo_lang_starknet::compile::compile_prepared_db;
use cairo_lang_starknet_classes::contract_class::ContractClass;
use cairo_lang_utils::CloneableDatabase;
use cairo_lang_utils::bigint::{BigIntAsHex, BigUintAsHex};
use itertools::Itertools;
use salsa::Database;
use starknet_core::types::contract::SierraClass;
use starknet_core::utils::starknet_keccak;
use std::collections::{HashMap, HashSet};
use std::sync::{Arc, Mutex};
use tracing::{trace, trace_span};

use super::compiler::SelectedContracts;
use crate::compiler::CairoCompilationUnit;
use crate::compiler::helpers::{build_compiler_config, collect_main_crate_ids};
use crate::compiler::incremental::IncrementalContext;
use crate::compiler::plugin::class_hash_forwarding::CLASS_HASH_MODULE_SUFFIX;
use crate::core::Workspace;

pub struct ForwardingCompilation {
    /// Compiled classes, in the order of the selected contracts.
    pub classes: Vec<ContractClass>,
    /// Class-hash accessors asked for on this db after the forwarding passes that do not belong
    /// to any selected contract (see [`compile_with_forwarding`]).
    pub unresolved: ClassHashUsage,
}

struct DiscoveredContract {
    deps: HashSet<String>,
    class: ContractClass,
}

/// Compiles `contracts` with their forwarded class hashes resolved: contracts are compiled in
/// dependency order, each pass supplying the hashes computed by the previous ones.
///
/// Leaves the resolved hashes installed on `db`, so anything compiled on it afterwards (e.g. a test
/// program embedding these contracts) sees the same values. Requests for contracts outside
/// `contracts` fall through to the returned `unresolved` handle instead of failing.
pub fn compile_with_forwarding(
    db: &mut dyn CloneableDatabase,
    unit: &CairoCompilationUnit,
    ctx: &Arc<IncrementalContext>,
    ws: &Workspace<'_>,
    contracts: &SelectedContracts,
) -> Result<ForwardingCompilation> {
    trace!(contracts = ?contracts.paths);

    {
        let main_crate_ids = collect_main_crate_ids(unit, db);
        let mut diagnostics_config =
            build_compiler_config(db, unit, &main_crate_ids, ctx, ctx.warning_collector(), ws);
        ensure_diagnostics(db, &mut diagnostics_config.diagnostics_reporter)?;
    }

    let span = trace_span!("compile_starknet");
    let _guard = span.enter();
    compile_contracts_in_forwarding_order(db, unit, contracts)
}

fn compile_contracts_in_forwarding_order(
    db: &mut dyn CloneableDatabase,
    unit: &CairoCompilationUnit,
    contracts: &SelectedContracts,
) -> Result<ForwardingCompilation> {
    let target_keys = contracts
        .paths
        .iter()
        .map(|contract_path| {
            (
                class_hash_provider_key(contract_path),
                contract_path.clone(),
            )
        })
        .collect::<HashMap<_, _>>();

    // Discovery: compile every contract in one parallel batch, answering each class-hash request
    // with a placeholder unique to the requested contract. The plugin cannot tell which contract
    // is asking, but a placeholder present in a compiled class is that class's dependency.
    let discovery = Arc::new(DiscoveryConstPlugin::default());
    db.set_external_const_plugins(vec![discovery.clone()]);
    let classes = compile_prepared_db(
        db,
        &contracts.declarations(db)?.iter().collect_vec(),
        silent_compiler_config(unit),
    )?;
    let placeholders = discovery.placeholders();
    let discovered = contracts
        .paths
        .iter()
        .zip(classes)
        .map(|(contract_path, class)| {
            let deps = placeholders
                .iter()
                .filter(|(_, placeholder)| class.sierra_program.contains(placeholder))
                .map(|(key, _)| key.clone())
                .collect();
            (
                class_hash_provider_key(contract_path),
                DiscoveredContract { deps, class },
            )
        })
        .collect::<HashMap<_, _>>();

    for (key, contract) in discovered.iter() {
        let contract_path = target_keys.get(key).expect("key exists");
        ensure!(
            !contract.deps.contains(key),
            "contract `{contract_path}` cannot statically forward to its own class hash. Use a \
             dynamic (storage-backed) `ForwardingClassHash` implementation instead."
        );
        let unknown = contract
            .deps
            .iter()
            .filter(|dep| !target_keys.contains_key(*dep))
            .map(|dep| describe_key(dep))
            .sorted()
            .collect_vec();
        ensure!(
            unknown.is_empty(),
            "contract `{contract_path}` forwards to contract(s) that are not included in this \
             build: {}. Add them with `build-external-contracts` or fix the forwarding target.",
            unknown.join(", ")
        );
    }

    let mut known = HashMap::<String, BigIntAsHex>::new();
    let mut classes_by_key = HashMap::<String, ContractClass>::new();
    for (key, contract) in discovered.iter() {
        if contract.deps.is_empty() {
            // Contains no placeholder, so this artifact is already final.
            known.insert(
                key.clone(),
                BigIntAsHex::from(starknet_class_hash(&contract.class)?.to_biguint()),
            );
            classes_by_key.insert(key.clone(), contract.class.clone());
        }
    }

    let mut remaining = target_keys
        .keys()
        .filter(|key| !classes_by_key.contains_key(*key))
        .cloned()
        .collect::<HashSet<_>>();

    while !remaining.is_empty() {
        let ready = remaining
            .iter()
            .filter(|key| {
                discovered
                    .get(*key)
                    .expect("dependencies exist")
                    .deps
                    .iter()
                    .all(|dep| known.contains_key(dep))
            })
            .cloned()
            .sorted()
            .collect_vec();

        if ready.is_empty() {
            let cycle_members = remaining
                .iter()
                .map(|key| target_keys.get(key).expect("key exists").clone())
                .sorted()
                .join(", ");
            bail!("forwarding cycle detected among contracts: {cycle_members}");
        }

        // A round's contracts only depend on prior rounds, never each other, so one install
        // covers the whole batch, compiled together like the non-forwarding path.
        db.set_external_const_plugins(vec![Arc::new(ResolvingConstPlugin {
            known: known.clone(),
        })]);
        let ready_paths = ready
            .iter()
            .map(|key| {
                target_keys
                    .get(key)
                    .expect("ready key must refer to a contract")
                    .clone()
            })
            .collect_vec();
        let ready_contracts = contracts.declarations_of(db, &ready_paths)?;
        let classes = compile_prepared_db(
            db,
            &ready_contracts.iter().collect_vec(),
            silent_compiler_config(unit),
        )?;

        for (key, class) in ready.into_iter().zip(classes) {
            known.insert(
                key.clone(),
                BigIntAsHex::from(starknet_class_hash(&class)?.to_biguint()),
            );
            classes_by_key.insert(key.clone(), class);
            remaining.remove(&key);
        }
    }

    let unresolved: ClassHashUsage = Default::default();
    db.set_external_const_plugins(vec![
        Arc::new(ResolvingConstPlugin { known }),
        Arc::new(RecordingConstPlugin {
            recorded: unresolved.clone(),
        }),
    ]);

    let classes = contracts
        .paths
        .iter()
        .map(|contract_path| {
            let key = class_hash_provider_key(contract_path);
            classes_by_key
                .remove(&key)
                .with_context(|| format!("missing compiled class for `{contract_path}`"))
        })
        .collect::<Result<Vec<_>>>()?;
    Ok(ForwardingCompilation {
        classes,
        unresolved,
    })
}

fn starknet_class_hash(class: &ContractClass) -> Result<starknet_core::types::Felt> {
    let class: SierraClass = serde_json::from_value(serde_json::to_value(class)?)
        .context("failed to convert Starknet contract class for class hash computation")?;
    Ok(class.class_hash()?)
}

/// Full path of the reserved extern in the class-hash sibling module for `contract_path`.
fn class_hash_provider_key(contract_path: &str) -> String {
    let (parent, leaf) = match contract_path.rsplit_once("::") {
        Some((parent, leaf)) => (format!("{parent}::"), leaf),
        None => (String::new(), contract_path),
    };
    format!("{parent}{leaf}{CLASS_HASH_MODULE_SUFFIX}::{EXTERNALLY_PROVIDED_CONST}")
}

/// Contract path for a provider key, for diagnostics. Falls back to the raw key if malformed.
fn describe_key(key: &str) -> String {
    let suffix = format!("{CLASS_HASH_MODULE_SUFFIX}::{EXTERNALLY_PROVIDED_CONST}");
    let Some(without_suffix) = key.strip_suffix(&suffix) else {
        return key.to_string();
    };
    without_suffix.to_string()
}

/// Handle returned by [`install_default_class_hash_plugin`], shared with (not reinstalled by) any
/// caller that later wants to check it via [`ensure_forwarding_unused`].
pub type ClassHashUsage = Arc<Mutex<HashSet<String>>>;

/// Default fallback so the class-hash extern always resolves to *something* (a contract's
/// `class_hash()` can get compiled even when unused, e.g. by a `lib` target). Answers `0` and
/// records every path asked about, so a caller can later check `ensure_forwarding_unused` to tell
/// real forwarding usage from incidental compilation.
///
/// Call once per db (`CompilerRepository::compile` does this) and reuse the returned handle -
/// installing a second plugin on the same db has caused a process abort when that db later loads
/// cached incremental artifacts.
pub fn install_default_class_hash_plugin(db: &mut dyn CloneableDatabase) -> ClassHashUsage {
    let recorded: ClassHashUsage = Default::default();
    db.set_external_const_plugins(vec![Arc::new(RecordingConstPlugin {
        recorded: recorded.clone(),
    })]);
    recorded
}

/// Errors if the class-hash extern was actually used, i.e. some contract really does forward.
/// Only call after a reachability-scoped compile (starknet-contract, test, executable) - never
/// after a whole-program one (`lib`), which would false-positive on any unused accessor.
pub fn ensure_forwarding_unused(recorded: &ClassHashUsage, help: &str) -> Result<()> {
    let contracts = recorded_contracts(recorded);
    ensure!(
        contracts.is_empty(),
        "contract(s) use static forwarding but it did not run for this build: {}. {help}",
        contracts.join(", ")
    );
    Ok(())
}

/// Errors if, after [`compile_with_forwarding`], the class hash of a contract outside the
/// compiled set was asked for, i.e. some code forwards to a contract this build does not know.
pub fn ensure_forwarding_resolved(unresolved: &ClassHashUsage) -> Result<()> {
    let contracts = recorded_contracts(unresolved);
    ensure!(
        contracts.is_empty(),
        "forwarding to contract(s) that are not included in this build: {}. Add them with \
         `build-external-contracts` or fix the forwarding target.",
        contracts.join(", ")
    );
    Ok(())
}

fn recorded_contracts(recorded: &ClassHashUsage) -> Vec<String> {
    recorded
        .lock()
        .expect("recording provider mutex poisoned")
        .iter()
        .map(|key| describe_key(key))
        .sorted()
        .collect_vec()
}

/// Answers `0` for every class-hash request, recording what was asked.
#[derive(Debug)]
struct RecordingConstPlugin {
    recorded: ClassHashUsage,
}

impl ExternalConstPlugin for RecordingConstPlugin {
    fn provide<'db>(
        &self,
        db: &'db dyn Database,
        extern_id: ExternFunctionId<'db>,
        ty: TypeId<'db>,
    ) -> Option<Maybe<ConstValueId<'db>>> {
        self.recorded
            .lock()
            .expect("recording provider mutex poisoned")
            .insert(extern_id.full_path(db));
        Some(Ok(ConstValueId::from_int(
            db,
            ty,
            &BigIntAsHex::from(0).value,
        )))
    }
}

/// Answers every class-hash request with a placeholder unique to the requested contract, and
/// remembers which placeholder stands for which contract.
#[derive(Debug, Default)]
struct DiscoveryConstPlugin {
    placeholders: Mutex<HashMap<String, BigUintAsHex>>,
}

impl DiscoveryConstPlugin {
    /// Placeholders handed out so far, by provider key.
    fn placeholders(&self) -> HashMap<String, BigUintAsHex> {
        self.placeholders
            .lock()
            .expect("discovery provider mutex poisoned")
            .clone()
    }
}

impl ExternalConstPlugin for DiscoveryConstPlugin {
    fn provide<'db>(
        &self,
        db: &'db dyn Database,
        extern_id: ExternFunctionId<'db>,
        ty: TypeId<'db>,
    ) -> Option<Maybe<ConstValueId<'db>>> {
        let key = extern_id.full_path(db);
        // Keyed by the accessor path, so it is stable and cannot collide across contracts. A
        // clash with a genuine constant in user code is as unlikely as a hash collision.
        let placeholder = BigUintAsHex::from(starknet_keccak(key.as_bytes()).to_biguint());
        let value =
            ConstValueId::from_int(db, ty, &BigIntAsHex::from(placeholder.value.clone()).value);
        self.placeholders
            .lock()
            .expect("discovery provider mutex poisoned")
            .insert(key, placeholder);
        Some(Ok(value))
    }
}

/// Answers class-hash requests from a fixed map, leaving unknown ones to the next plugin.
#[derive(Debug)]
struct ResolvingConstPlugin {
    known: HashMap<String, BigIntAsHex>,
}

impl ExternalConstPlugin for ResolvingConstPlugin {
    fn provide<'db>(
        &self,
        db: &'db dyn Database,
        extern_id: ExternFunctionId<'db>,
        ty: TypeId<'db>,
    ) -> Option<Maybe<ConstValueId<'db>>> {
        let value = self.known.get(&extern_id.full_path(db))?;
        Some(Ok(ConstValueId::from_int(db, ty, &value.value)))
    }
}

fn silent_compiler_config(unit: &CairoCompilationUnit) -> CompilerConfig<'static> {
    CompilerConfig {
        diagnostics_reporter: DiagnosticsReporter::ignoring()
            .allow_warnings()
            .with_crates(&[]),
        replace_ids: unit.compiler_config.sierra_replace_ids,
        add_statements_functions: unit.compiler_config.add_statements_functions_debug_info,
        add_statements_code_locations: unit
            .compiler_config
            .add_statements_code_locations_debug_info,
        add_functions_debug_info: unit.compiler_config.add_functions_debug_info,
        add_type_names: unit.compiler_config.add_types_debug_info,
    }
}
