//! Static contract forwarding: injects forwarding targets' class hashes into dependents' Sierra
//! generation via the reserved `__externally_provided_const__` extern. The per-contract
//! class-hash accessor is generated by Scarb (`plugin::class_hash_forwarding`), not Cairo.

use anyhow::{Context, Result, bail, ensure};
use cairo_lang_compiler::diagnostics::DiagnosticsReporter;
use cairo_lang_compiler::{CompilerConfig, ensure_diagnostics};
use cairo_lang_defs::ids::{ExternFunctionId, TopLevelLanguageElementId};
use cairo_lang_diagnostics::Maybe;
use cairo_lang_semantic::TypeId;
use cairo_lang_semantic::items::constant::ConstValueId;
use cairo_lang_sierra_generator::db::{ExternalConstPlugin, SierraGenGroup};
use cairo_lang_starknet::compile::compile_prepared_db;
use cairo_lang_starknet::contract::ContractDeclaration;
use cairo_lang_starknet_classes::contract_class::ContractClass;
use cairo_lang_utils::CloneableDatabase;
use cairo_lang_utils::bigint::BigIntAsHex;
use itertools::Itertools;
use salsa::Database;
use scarb_ui::Ui;
use starknet_core::types::contract::SierraClass;
use std::collections::{HashMap, HashSet};
use std::sync::{Arc, Mutex};
use tracing::{trace, trace_span};

use super::compiler::find_project_contracts_silent;
use super::contract_selector::ContractSelector;
use crate::compiler::CairoCompilationUnit;
use crate::compiler::helpers::{build_compiler_config, collect_main_crate_ids};
use crate::compiler::incremental::IncrementalContext;
use crate::compiler::plugin::class_hash_forwarding::CLASS_HASH_MODULE_SUFFIX;
use crate::core::Workspace;

pub(super) struct ForwardingCompilation {
    pub contract_paths: Vec<String>,
    pub classes: Vec<ContractClass>,
}

struct DiscoveredContract {
    deps: HashSet<String>,
    class: ContractClass,
}

pub(super) fn compile_with_forwarding(
    db: &mut dyn CloneableDatabase,
    unit: &CairoCompilationUnit,
    ctx: &Arc<IncrementalContext>,
    ws: &Workspace<'_>,
    external_contracts: Option<Vec<ContractSelector>>,
) -> Result<ForwardingCompilation> {
    let main_crate_ids = collect_main_crate_ids(unit, db);
    let contract_paths = {
        let contracts = find_project_contracts_silent(
            db,
            ws.config().ui(),
            unit,
            main_crate_ids.clone(),
            external_contracts.clone(),
        )?;
        contracts
            .iter()
            .map(|decl| decl.module_id().full_path(db).to_string())
            .collect_vec()
    };
    trace!(contracts = ?contract_paths);

    {
        let mut diagnostics_config =
            build_compiler_config(db, unit, &main_crate_ids, ctx, ctx.warning_collector(), ws);
        ensure_diagnostics(db, &mut diagnostics_config.diagnostics_reporter)?;
    }

    let span = trace_span!("compile_starknet");
    let classes = {
        let _guard = span.enter();
        compile_contracts_in_forwarding_order(
            db,
            unit,
            ws.config().ui(),
            external_contracts.clone(),
            &contract_paths,
        )?
    };
    install_default_class_hash_plugin(db);

    Ok(ForwardingCompilation {
        contract_paths,
        classes,
    })
}

fn compile_contracts_in_forwarding_order(
    db: &mut dyn CloneableDatabase,
    unit: &CairoCompilationUnit,
    ui: Ui,
    external_contracts: Option<Vec<ContractSelector>>,
    contract_paths: &[String],
) -> Result<Vec<ContractClass>> {
    let target_keys = contract_paths
        .iter()
        .map(|contract_path| {
            (
                class_hash_provider_key(contract_path),
                contract_path.clone(),
            )
        })
        .collect::<HashMap<_, _>>();

    // Discovery: compile each contract solo, answering 0 to any forwarding request while
    // recording what was asked. Sequential and deliberately so: mutating a cloned db's plugin
    // list from a parallel worker deadlocked (Salsa blocks a writer until sibling clones drop).
    let mut discovered = HashMap::<String, DiscoveredContract>::new();
    for contract_path in contract_paths {
        let recorded = Arc::new(Mutex::new(HashSet::<String>::new()));
        install_recording_plugin(db, recorded.clone());
        let contract = find_project_contract_by_path(
            db,
            ui.clone(),
            unit,
            external_contracts.clone(),
            contract_path,
        )?;
        let class = compile_prepared_db(db, &[&contract], silent_compiler_config(unit))?
            .into_iter()
            .exactly_one()?;
        let deps = recorded
            .lock()
            .expect("recording provider mutex poisoned")
            .clone();
        discovered.insert(
            class_hash_provider_key(contract_path),
            DiscoveredContract { deps, class },
        );
    }

    for (key, contract) in discovered.iter() {
        let contract_path = target_keys.get(key).expect("key exists");
        ensure!(
            !contract.deps.contains(key),
            "contract `{contract_path}` cannot statically forward to its own class hash. Use a \
             dynamic (storage-backed) `ForwardingClassHash` implementation instead."
        );
        let unknown = contract
            .deps
            .iter()
            .filter(|dep| !target_keys.contains_key(*dep))
            .map(|dep| describe_key(dep))
            .sorted()
            .collect_vec();
        ensure!(
            unknown.is_empty(),
            "contract `{contract_path}` forwards to contract(s) that are not included in this \
             build: {}. Add them with `build-external-contracts` or fix the forwarding target.",
            unknown.join(", ")
        );
    }

    let mut known = HashMap::<String, BigIntAsHex>::new();
    let mut classes_by_key = HashMap::<String, ContractClass>::new();
    for (key, contract) in discovered.iter() {
        if contract.deps.is_empty() {
            // Never invoked the recording provider, so this artifact is unaffected by it.
            known.insert(
                key.clone(),
                BigIntAsHex::from(starknet_class_hash(&contract.class)?.to_biguint()),
            );
            classes_by_key.insert(key.clone(), contract.class.clone());
        }
    }

    let mut remaining = contract_paths
        .iter()
        .map(|contract| class_hash_provider_key(contract))
        .filter(|key| !classes_by_key.contains_key(key))
        .collect::<HashSet<_>>();

    while !remaining.is_empty() {
        let ready = remaining
            .iter()
            .filter(|key| {
                discovered
                    .get(*key)
                    .expect("dependencies exist")
                    .deps
                    .iter()
                    .all(|dep| known.contains_key(dep))
            })
            .cloned()
            .sorted()
            .collect_vec();

        if ready.is_empty() {
            let cycle_members = remaining
                .iter()
                .map(|key| target_keys.get(key).expect("key exists").clone())
                .sorted()
                .join(", ");
            bail!("forwarding cycle detected among contracts: {cycle_members}");
        }

        // A round's contracts only depend on prior rounds, never each other, so one install
        // covers the whole batch, compiled together like the non-forwarding path.
        install_resolving_plugin(db, known.clone());
        let ready_contracts = ready
            .iter()
            .map(|key| {
                let contract_path = target_keys
                    .get(key)
                    .expect("ready key must refer to a contract");
                find_project_contract_by_path(
                    db,
                    ui.clone(),
                    unit,
                    external_contracts.clone(),
                    contract_path,
                )
            })
            .collect::<Result<Vec<_>>>()?;
        let classes = compile_prepared_db(
            db,
            &ready_contracts.iter().collect::<Vec<_>>(),
            silent_compiler_config(unit),
        )?;

        for (key, class) in ready.into_iter().zip(classes) {
            known.insert(
                key.clone(),
                BigIntAsHex::from(starknet_class_hash(&class)?.to_biguint()),
            );
            classes_by_key.insert(key.clone(), class);
            remaining.remove(&key);
        }
    }

    contract_paths
        .iter()
        .map(|contract_path| {
            let key = class_hash_provider_key(contract_path);
            classes_by_key
                .remove(&key)
                .with_context(|| format!("missing compiled class for `{contract_path}`"))
        })
        .collect()
}

fn starknet_class_hash(class: &ContractClass) -> Result<starknet_core::types::Felt> {
    let class: SierraClass = serde_json::from_value(serde_json::to_value(class)?)
        .context("failed to convert Starknet contract class for class hash computation")?;
    Ok(class.class_hash()?)
}

fn find_project_contract_by_path<'db>(
    db: &'db dyn CloneableDatabase,
    ui: Ui,
    unit: &CairoCompilationUnit,
    external_contracts: Option<Vec<ContractSelector>>,
    contract_path: &str,
) -> Result<ContractDeclaration<'db>> {
    find_project_contracts_silent(
        db,
        ui,
        unit,
        collect_main_crate_ids(unit, db),
        external_contracts,
    )?
    .into_iter()
    .find(|contract| contract.module_id().full_path(db) == contract_path)
    .with_context(|| format!("failed to find contract `{contract_path}`"))
}

/// Full path of the reserved extern in the class-hash sibling module for `contract_path`.
fn class_hash_provider_key(contract_path: &str) -> String {
    let (parent, leaf) = match contract_path.rsplit_once("::") {
        Some((parent, leaf)) => (format!("{parent}::"), leaf),
        None => (String::new(), contract_path),
    };
    format!("{parent}{leaf}{CLASS_HASH_MODULE_SUFFIX}::__externally_provided_const__")
}

/// Contract path for a provider key, for diagnostics. Falls back to the raw key if malformed.
fn describe_key(key: &str) -> String {
    let suffix = format!("{CLASS_HASH_MODULE_SUFFIX}::__externally_provided_const__");
    let Some(without_suffix) = key.strip_suffix(&suffix) else {
        return key.to_string();
    };
    without_suffix.to_string()
}

/// Handle returned by [`install_default_class_hash_plugin`], shared with (not reinstalled by) any
/// caller that later wants to check it via [`ensure_forwarding_unused`].
pub(crate) type ClassHashUsage = Arc<Mutex<HashSet<String>>>;

/// Default fallback so the class-hash extern always resolves to *something* (a contract's
/// `class_hash()` can get compiled even when unused, e.g. by a `lib` target). Answers `0` and
/// records every path asked about, so a caller can later check `ensure_forwarding_unused` to tell
/// real forwarding usage from incidental compilation.
///
/// Call once per db (`CompilerRepository::compile` does this) and reuse the returned handle -
/// installing a second plugin on the same db has caused a process abort when that db later loads
/// cached incremental artifacts.
pub(crate) fn install_default_class_hash_plugin(db: &mut dyn CloneableDatabase) -> ClassHashUsage {
    let recorded = Arc::new(Mutex::new(HashSet::new()));
    install_recording_plugin(db, recorded.clone());
    recorded
}

/// Errors if the class-hash extern was actually used, i.e. some contract really does forward.
/// Only call after a reachability-scoped compile (starknet-contract, test, executable) - never
/// after a whole-program one (`lib`), which would false-positive on any unused accessor.
pub(crate) fn ensure_forwarding_unused(recorded: &ClassHashUsage, help: &str) -> Result<()> {
    let used = recorded.lock().expect("recording provider mutex poisoned");
    let contracts = used
        .iter()
        .map(|key| describe_key(key))
        .sorted()
        .collect_vec();
    ensure!(
        contracts.is_empty(),
        "contract(s) use static forwarding but it did not run for this build: {}. {help}",
        contracts.join(", ")
    );
    Ok(())
}

#[derive(Debug)]
struct RecordingConstPlugin {
    recorded: Arc<Mutex<HashSet<String>>>,
}

impl ExternalConstPlugin for RecordingConstPlugin {
    fn provide<'db>(
        &self,
        db: &'db dyn Database,
        extern_id: ExternFunctionId<'db>,
        ty: TypeId<'db>,
    ) -> Option<Maybe<ConstValueId<'db>>> {
        self.recorded
            .lock()
            .expect("recording provider mutex poisoned")
            .insert(extern_id.full_path(db));
        Some(Ok(ConstValueId::from_int(
            db,
            ty,
            &BigIntAsHex::from(0).value,
        )))
    }
}

#[derive(Debug)]
struct ResolvingConstPlugin {
    known: HashMap<String, BigIntAsHex>,
}

impl ExternalConstPlugin for ResolvingConstPlugin {
    fn provide<'db>(
        &self,
        db: &'db dyn Database,
        extern_id: ExternFunctionId<'db>,
        ty: TypeId<'db>,
    ) -> Option<Maybe<ConstValueId<'db>>> {
        let path = extern_id.full_path(db);
        // Unreachable: discovery already validated every dep as known before readiness.
        let value = self
            .known
            .get(&path)
            .unwrap_or_else(|| panic!("internal error: no resolved class hash for `{path}`"));
        Some(Ok(ConstValueId::from_int(db, ty, &value.value)))
    }
}

fn install_recording_plugin(db: &mut dyn CloneableDatabase, recorded: Arc<Mutex<HashSet<String>>>) {
    db.set_external_const_plugins(vec![Arc::new(RecordingConstPlugin { recorded })]);
}

fn install_resolving_plugin(db: &mut dyn CloneableDatabase, known: HashMap<String, BigIntAsHex>) {
    db.set_external_const_plugins(vec![Arc::new(ResolvingConstPlugin { known })]);
}

fn silent_compiler_config(unit: &CairoCompilationUnit) -> CompilerConfig<'static> {
    CompilerConfig {
        diagnostics_reporter: DiagnosticsReporter::ignoring()
            .allow_warnings()
            .with_crates(&[]),
        replace_ids: unit.compiler_config.sierra_replace_ids,
        add_statements_functions: unit.compiler_config.add_statements_functions_debug_info,
        add_statements_code_locations: unit
            .compiler_config
            .add_statements_code_locations_debug_info,
        add_functions_debug_info: unit.compiler_config.add_functions_debug_info,
        add_type_names: unit.compiler_config.add_types_debug_info,
    }
}
