name: Trigger Maat experiment
on:
  workflow_run:
    workflows: ["Publish Built-in Plugins"]
    types: [completed]

jobs:
  trigger-maat-experiment:
    name: Trigger Maat experiment
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from tag
        env:
          RAW_REF: ${{ github.event.workflow_run.head_branch }}
        run: |
          VERSION=${RAW_REF}

          # Strip 'v' prefix from the version if it exists
          VERSION=${VERSION#v}

          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          
      - name: Trigger Maat experiment
        env:
          GH_TOKEN: ${{ secrets.MAAT_EXPERIMENTS_DISPATCH_TOKEN }}
        run: |
          gh workflow run experiment.yml \
            --repo software-mansion/maat \
            --ref main \
            -f workspace="release" \
            -f scarb="$VERSION" \
            -f notify_team="true"