name: Release

on:
  push:
    tags:
      - v[0-9]+.*

permissions:
  contents: read

jobs:
  check:
    uses: ./.github/workflows/_check-release.yml

  release:
    uses: ./.github/workflows/_build-release.yml
    with:
      scarb-tag: ${{ github.ref_name }}
      full-verify: true

  draft:
    name: draft release
    runs-on: ubuntu-latest
    needs: [ check, release ]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          path: artifacts-dl

      - name: Unpack artifacts to staging directory
        run: |
          mkdir -p artifacts
          mv artifacts-dl/build-*/scarb-* artifacts/
          mv artifacts-dl/checksums/* artifacts/
          ls -lh artifacts/

      - name: Determine release notes start tag
        run: |
          if [[ "$RELEASE_TAG" == *-rc* ]]; then
            # because the release is a release candidate, we want to include pre-releases when determining the start tag for the release notes
            RELEASE_NOTES_START_TAG =$(gh release list --json tagName --limit 1 --exclude-drafts --jq '.[0].tagName')
          else
            # because the release is not a release candidate, we want to exclude pre-releases when determining the start tag for the release notes
            RELEASE_NOTES_START_TAG=$(gh release list --json tagName --limit 1 --exclude-pre-releases --exclude-drafts --jq '.[0].tagName')
          fi
          echo "RELEASE_NOTES_START_TAG=${RELEASE_NOTES_START_TAG}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.ref_name }}

      - name: Draft GitHub release
        run: |
          gh release create \
            "${RELEASE_TAG}" \
            ./artifacts/* \
            --draft \
            --title "${RELEASE_TAG}" \
            --generate-notes \
            --verify-tag \
            --notes-start-tag ${RELEASE_NOTES_START_TAG} \
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.ref_name }}

  publish_plugins:
    name: publish plugins
    needs: [ draft ]
    permissions:
      contents: read
    uses: ./.github/workflows/publish_plugins.yml
    with:
      version_tag: ${{ github.ref_name }}
    secrets:
      SCARB_REGISTRY_AUTH_TOKEN: ${{ secrets.SCARB_REGISTRY_AUTH_TOKEN }}
      SCARB_DEV_REGISTRY_AUTH_TOKEN: ${{ secrets.SCARB_DEV_REGISTRY_AUTH_TOKEN }}
      SLACK_PUBLISH_PLUGINS_FAILURE_WEBHOOK_URL: ${{ secrets.SLACK_PUBLISH_PLUGINS_FAILURE_WEBHOOK_URL }}
