name: Trigger Release Experiment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'main'

# Supported branch partterns:
# release/1.2.3, release/v1.2.3, release-1.2.3, release-v1.2.3

jobs:
  dispatch-experiment:
    if: startsWith(github.head_ref, 'release/') || startsWith(github.head_ref, 'release-')
    runs-on: ubuntu-latest

    steps: 
      - name: Extract version from branch name
        env:
          RAW_REF: ${{ github.head_ref }}
        run: |
          VERSION=${RAW_REF}

          # Strip 'release/' or 'release-' prefix from the branch name to get the version
          VERSION=${VERSION#release/}
          VERSION=${VERSION#release-}

          # Strip 'v' prefix from the version if it exists
          VERSION=${VERSION#v}

          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Trigger Release Experiment
        env:
          GH_TOKEN: ${{ secrets.MAAT_EXPERIMENTS_DISPATCH_TOKEN }}
        run: |
          gh workflow run experiment.yml \
            --repo software-mansion/maat \
            --ref main \
            -f workspace="release" \
            -f scarb="$VERSION" \
            -f notify_team="true"