[package]
name = "fibonacci"
version.workspace = true

[scripts]
test.workspace = true

[tool]
snforge.workspace = true

[dependencies]
addition = { path = "../addition" }

[dev-dependencies]
cairo_test.workspace = true
